In [4]:
import pandas as pd

In [5]:
res_file = 'results_log_regression.csv'
df = pd.read_csv(res_file)

In [16]:
# sort df by accuracy
df.sort_values(by=['f1_score'], inplace=True, ascending=False)
df.head(10)

,scaling,imputation,cat_age,downsampling_freq,accuracy,precision,recall,f1_score
38,standard,drop,False,0.9,0.949199,0.567799,0.571684,0.569735
53,NaN,mode,False,0.8,0.942429,0.515364,0.636795,0.569680
69,NaN,nancat,False,0.8,0.942446,0.515487,0.636516,0.569644
57,NaN,drop,True,0.8,0.943056,0.512869,0.640095,0.569463
46,standard,nancat,False,0.9,0.949212,0.578008,0.560581,0.569161
30,standard,mode,False,0.9,0.949212,0.578053,0.560302,0.569039
61,NaN,drop,False,0.8,0.943109,0.513338,0.635336,0.567859
9,minmax,drop,True,0.8,0.942969,0.512353,0.635336,0.567255
65,NaN,nancat,True,0.8,0.942129,0.513367,0.632607,0.566783
49,NaN,mode,True,0.8,0.942129,0.513367,0.632607,0.566783