In [2]:
import pandas as pd

In [3]:
res_file = 'results_log_regression.csv'
df = pd.read_csv(res_file)

In [6]:
# sort df by accuracy
df.sort_values(by=['recall'], inplace=True, ascending=False)
df.head(10)

,scaling,imputation,cat_age,downsampling_freq,accuracy,precision,recall,f1_score
36,standard,drop,False,0.7,0.899447,0.349987,0.827186,0.491864
44,standard,nancat,False,0.7,0.899561,0.354177,0.823841,0.495384
28,standard,mode,False,0.7,0.899577,0.354219,0.823841,0.495425
32,standard,drop,True,0.7,0.908372,0.370865,0.800416,0.506875
40,standard,nancat,True,0.7,0.908766,0.376495,0.799553,0.511931
24,standard,mode,True,0.7,0.908883,0.376842,0.799553,0.512252
48,NaN,mode,True,0.7,0.924403,0.424789,0.743439,0.540656
56,NaN,drop,True,0.7,0.925154,0.422628,0.743308,0.538868
52,NaN,mode,False,0.7,0.924102,0.423524,0.742881,0.539483
64,NaN,nancat,True,0.7,0.924453,0.424920,0.742602,0.540541